# Làm quen thư viên Pandas trong python

### Hướng dẫn thực hành (Interactive Learning)
Trong bài này, bạn sẽ thực hành thao tác với dữ liệu (Data Manipulation) bằng thư viện **Pandas**.

**Kiến thức cốt lõi:** Các thao tác lọc (filter), nhóm (group), và thống kê (aggregate) trên DataFrame.

**Ứng dụng thực tế:** Pandas giống như Excel nhưng sử dụng code, cho phép bạn xử lý hàng triệu dòng dữ liệu trong tích tắc. Đây là công cụ không thể thiếu của các Data Analyst và Data Scientist để dọn dẹp và hiểu dữ liệu trước khi đưa vào mô hình AI.

> **Cách chạy code:** Hãy đọc kỹ yêu cầu của mỗi bài tập (các ô text). Sau đó, click vào ô code (có nền xám bên dưới) và tự tay gõ code giải quyết bài toán. Nhấn nút **Run (▶)** ở góc phải của mỗi ô, hoặc sử dụng biểu tượng Play trên thanh công cụ để chạy thử. Hãy thoải mái sửa đổi code và chạy lại để xem kết quả khác biệt ra sao nhé!

[Pandas](http://pandas.pydata.org) cung cấp cấu trúc dữ liệu cấp cao và các hàm được thiết kế để làm việc với dữ liệu có cấu trúc hoặc dữ liệu dạng bảng nhanh chóng và dễ dàng. Đối tượng chính trong mà chúng ta sẽ sử dụng là `DataFrame`, cấu trúc dữ liệu dạng bảng, định hướng cột và hàng.

Pandas kết hợp các ý tưởng tính toán mảng, hiệu suất cao của NumPy với khả năng thao tác dữ liệu linh hoạt dưới dạng bảng tính hay cơ sở dữ liệu quan hệ. Mặc dù Pandas áp dụng hầu hết các điểm mạnh từ NumPy, tuy nhiên điểm khác biệt đáng kể nhất của Pandas là được thiết kế để làm việc với dữ liệu dạng bảng hoặc không đồng nhất. Ngược lại, NumPy phù hợp làm việc với dữ liệu mảng số đồng nhất.

In [5]:
# Bắt đầu bằng việc nhập các thư viện cần thiết
# Hãy nhớ chạy ô code này đầu tiên để nạp thư viện nhé!
import pandas as pd
import numpy as np

# Cấu trúc dữ liệu <a name="structures"></a>

## Dữ liệu dạng mảng (Series) <a name="series"></a>

`Series` là một đối tượng giống như mảng một chiều chứa một chuỗi các giá trị và một mảng nhãn dữ liệu liên quan được gọi là chỉ mục của nó.

Dưới đây là cách tạo một mảng bằng pandas

In [6]:
data = pd.Series([4, 7, -5, 3])

Print mảng vừa được tạo

In [7]:
data

0    4
1    7
2   -5
3    3
dtype: int64

Các chỉ mục của mảng nằm ở bên trái và các giá trị ở bên phải. 

Nếu không định nghĩa chỉ mục cho từng mảng, thì chỉ mục mặc định của mảng là các số nguyên từ 0 đến N-1.

Chúng ta có thể lấy các giá trị của mảng bảng cách:

In [8]:
data.values

array([ 4,  7, -5,  3])

Chúng ta có thể chỉ định các chỉ mục tùy chỉnh khi khởi tạo một mảng

In [9]:
data2 = pd.Series([4, 7, -5, 3], index=["a", "b", "c", "d"])

In [10]:
data2

a    4
b    7
c   -5
d    3
dtype: int64

Chúng ta có thể tạo một mảng từ một dictionary

In [11]:
cities = {"Glasgow" : 599650, "Edinburgh" : 464990, "Aberdeen" : 196670, "Dundee" : 147710}
data3 = pd.Series(cities)

In [12]:
data3

Glasgow      599650
Edinburgh    464990
Aberdeen     196670
Dundee       147710
dtype: int64

## DataFrame <a name="dataframe"></a>

Dataframe biểu thị một bảng dữ liệu hình chữ nhật và chứa một tập hợp các cột được sắp xếp theo thứ tự, mỗi cột có thể là một loại giá trị khác nhau. DataFrame có cả chỉ mục hàng và cột.

Cách đơn giản nhất để tạo ra một dataframe là từ một dictionary:

In [28]:
data = {"cities" : ["Glasgow", "Edinburgh", "Aberdeen", "Dundee"],
        "population" : [599650, 464990, 196670, 147710],
        "year" : [2011, 2013, 2013, 2013]}
df = pd.DataFrame(data)

kiểm tra df vừa mới được tạo:

In [34]:
df.cities #call column
df.iloc[0:3:2] #call row 1 and row 3

Bạn có thể sắp xếp thứ tự các cột, chỉ mục của các hàng trong quá trình tạo một dataframe:

In [15]:
df2 = pd.DataFrame(data, columns=["year", "cities", "population"], index=["a", "b", "c", "d"])
df2

   year     cities  population
a  2011    Glasgow      599650
b  2013  Edinburgh      464990
c  2013   Aberdeen      196670
d  2013     Dundee      147710

Bạn có thể chọn 1 cột trong dataframe bằng cách:
```python
df2["cities"]
```
Kết quả trả về sẽ là một mảng trong python:

In [16]:
df2["cities"]

a      Glasgow
b    Edinburgh
c     Aberdeen
d       Dundee
Name: cities, dtype: object

It is also possible to add and modify the columns of a DataFrame

Bạn cũng có thể thêm và sửa dữ liệu các cột trong python

In [17]:
df2["size"] = 100
df2

   year     cities  population  size
a  2011    Glasgow      599650   100
b  2013  Edinburgh      464990   100
c  2013   Aberdeen      196670   100
d  2013     Dundee      147710   100

In [18]:
df2["size"] = [175, 264, 65.1, 60]  # in km^2
df2

   year     cities  population   size
a  2011    Glasgow      599650  175.0
b  2013  Edinburgh      464990  264.0
c  2013   Aberdeen      196670   65.1
d  2013     Dundee      147710   60.0

# Một số hàm quan trọng <a name="ess_func"></a>

Trong phần này, chúng ta sẽ tìm hiểu các cơ chế cơ bản để tương tác với dữ liệu dạng mảng hoặc DaraFrame.

## Xoá cột hoặc chỉ mục <a name="removing"></a>

Chúng ta có thể sử dụng hàm `drop()` để xoá dữ liệu, nó có thể áp dụng được với cột và các chỉ mục:

In [19]:
# Tạo một dataframe mới:
data = np.reshape(np.arange(9), (3,3))
df = pd.DataFrame(data, index=["a", "b", "c"],
                  columns=["Edinburgh", "Glasgow", "Aberdeen"])

df

   Edinburgh  Glasgow  Aberdeen
a          0        1         2
b          3        4         5
c          6        7         8

In [20]:
df.drop("b")  # xoá hàng dựa vàoc chỉ mục

   Edinburgh  Glasgow  Aberdeen
a          0        1         2
c          6        7         8

In [21]:
# Bạn cũng có thể xoá các cột (axis=1 or axis="columns")
df.drop(["Aberdeen", "Edinburgh"], axis="columns")

   Glasgow
a        1
b        4
c        7

Lưu ý rằng dataframe gốc không thay đổi nếu chúng ta sử dụng: `df.drop()`. Bởi vì khi sử dụng `df.drop()`, nó giữ nguyên dữ liệu gốc và tạo ramột dataframe mới với dữ liệu mong muốn đã bị loại bỏ. 

Để áp dụng `.drop()` vào trực tiếp dataframe gốc, chúng ta có thể thực hiện bằng cách thêm argument: `inplace=True` vào hàm.

In [22]:
df

   Edinburgh  Glasgow  Aberdeen
a          0        1         2
b          3        4         5
c          6        7         8

## Indexing <a name="indexing"></a>

Chúng ta sử dụng `.iloc` để chỉ mục dữ liệu trong dataframe

In [23]:
data = np.reshape(np.arange(9), (3,3))
df = pd.DataFrame(data, index=["a", "b", "c"],
                  columns=["Edinburgh", "Glasgow", "Aberdeen"])

df

   Edinburgh  Glasgow  Aberdeen
a          0        1         2
b          3        4         5
c          6        7         8

In [24]:
# Thay vì df[2] (bị lỗi KeyError do tìm theo tên cột), dùng df.iloc[2] để lấy dòng theo vị trí:
df.iloc[2]

In [ ]:
df.iloc[2]  # this works and return a series

Bạn cũng có thể cắt một dataframe như bình thường:

In [ ]:
df.iloc[:2]

In [ ]:
df.iloc[2,0]

Khi các chỉ mục/tên cột của dataframe của bạn không phải là số nguyên, bạn có thể sử dụng `.loc` để lập chỉ mục:

In [ ]:
df2

In [ ]:
df2.loc["a", "size"]

## Tóm tắt và tính toán số liệu thống kê mô tả<a name="sums"></a>
`pandas` được trang bị các phương pháp toán học và thống kê phổ biến:

Tạo một dataframe mới:

In [ ]:
df = pd.DataFrame(np.arange(20).reshape(5,4),
                 columns=["a", "b", "c", "d"])
df

Tính tổng giá trị theo chiều dọc:

In [ ]:
df.sum()

Tính tổng giá trị theo chiều ngang:

In [ ]:
df.sum(axis="columns")

Tính giá trị trung bình theo chiều dọc:

In [ ]:
df.mean()

Tính tổng giá trị theo chiều ngang:

In [ ]:
df.mean(axis="columns")

Chúng ta có thể tính toán các bước trên bàng 1 hàng duy nhất, hàm: `describe()` 

Hàm `describe()`  sẽ tính toán các thông số thống kê mô tả của dataframe:

In [ ]:
df.describe()

Đây là một vài phương thức chính thường được sử dụng với Dataframe:

| Phương thức | Mô tả |
| -- | -- |
| count          | Trả ra kết quả số lượng giá trị khác null |
| describe       | Trả ra kết quả thống kê mô tả của dataframe |
| min, max       | Trả ra kết quả thấp nhất, cao nhất của dataframe |
| argmin, argmax | Trả ra chỉ mục của giá trị thấp nhất, cao nhất trong dataframe | 
| sum            | Trả ra kết quả tính tổng |
| mean           | Trả ra kết quả tính trung bình |
| median         | Trả ra kết quả tính trung vị |
| std            | Trả ra kết quả Độ lệch chuẩn
| value_counts() | Đếm số lần xuất hiện của từng phần tử duy nhất trong một cột |

### Bài tập 1

Lấy thông tin dữ liệu từ dataframe từ hàng 85 đến 97 từ dataframe dưới đây:

In [40]:
df = pd.DataFrame(np.reshape(np.arange(10000), (100,100)))

In [41]:
df.iloc[85:98]

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
85,8500,8501,8502,8503,8504,8505,8506,8507,8508,8509,...,8590,8591,8592,8593,8594,8595,8596,8597,8598,8599
86,8600,8601,8602,8603,8604,8605,8606,8607,8608,8609,...,8690,8691,8692,8693,8694,8695,8696,8697,8698,8699
87,8700,8701,8702,8703,8704,8705,8706,8707,8708,8709,...,8790,8791,8792,8793,8794,8795,8796,8797,8798,8799
88,8800,8801,8802,8803,8804,8805,8806,8807,8808,8809,...,8890,8891,8892,8893,8894,8895,8896,8897,8898,8899
89,8900,8901,8902,8903,8904,8905,8906,8907,8908,8909,...,8990,8991,8992,8993,8994,8995,8996,8997,8998,8999
90,9000,9001,9002,9003,9004,9005,9006,9007,9008,9009,...,9090,9091,9092,9093,9094,9095,9096,9097,9098,9099
91,9100,9101,9102,9103,9104,9105,9106,9107,9108,9109,...,9190,9191,9192,9193,9194,9195,9196,9197,9198,9199
92,9200,9201,9202,9203,9204,9205,9206,9207,9208,9209,...,9290,9291,9292,9293,9294,9295,9296,9297,9298,9299
93,9300,9301,9302,9303,9304,9305,9306,9307,9308,9309,...,9390,9391,9392,9393,9394,9395,9396,9397,9398,9399
94,9400,9401,9402,9403,9404,9405,9406,9407,9408,9409,...,9490,9491,9492,9493,9494,9495,9496,9497,9498,9499
95,9500,9501,9502,9503,9504,9505,9506,9507,9508,9509,...,9590,9591,9592,9593,9594,9595,9596,9597,9598,9599
96,9600,9601,9602,9603,9604,9605,9606,9607,9608,9609,...,9690,9691,9692,9693,9694,9695,9696,9697,9698,9699
97,9700,9701,9702,9703,9704,9705,9706,9707,9708,9709,...,9790,9791,9792,9793,9794,9795,9796,9797,9798,9799

### Bài tập 2
Tạo ra một dataframe có kích thước 3*3 chứa các giá trị là số nguyên ngẫu nhiên

Bình phương các giá trị trong dataframe đó:

In [39]:
# Tạo dataframe 3x3 với số nguyên ngẫu nhiên (ví dụ từ 0 tới 100)
df_random = pd.DataFrame(np.random.randint(0, 100, size=(3, 3)))
df_random

# Bình phương các giá trị trong dataframe
df_squared = df_random ** 2
df_squared

      0    1     2
0  2209   49  8100
1  1936  100  1225
2  3249   25  9216

### Bài tập 3

Lấy thông tin trung bình của các cột (theo chiều ngang) từ dataframe dưới đây:

In [42]:
df.mean(axis="columns")

0       49.5
1      149.5
2      249.5
3      349.5
4      449.5
       ...
95    9549.5
96    9649.5
97    9749.5
98    9849.5
99    9949.5
Length: 100, dtype: float64