# Đọc & xuất dữ liệu từ các file có định dạng khác nhau

### Hướng dẫn học tập (Interactive Learning)
Trong phần này, bạn sẽ được tìm hiểu về **Kỹ thuật Nhập/Xuất Dữ Liệu (I/O) trong Python** bằng thư viện Pandas.

**Kiến thức:** Cách đọc các định dạng file phổ biến như .csv, .xlsx, .json vào một Dataframe của Pandas.

**Ứng dụng thực tế:** Khi phân tích dữ liệu thực tế, dữ liệu hiếm khi ở sẵn trong code. Chúng thường được lưu trong các file, database hoặc được cung cấp qua API. Việc nắm vững cách đọc/ghi dữ liệu là bước đầu tiên và quan trọng nhất của mọi Data Scientist.

> **Cách chạy code:** Hãy click vào các ô code (có nền xám bên dưới) và nhấn nút **Run (▶)** ở góc phải của mỗi ô, hoặc sử dụng biểu tượng Play trên thanh công cụ để thực thi code. Bạn có thể thay đổi đường dẫn file hoặc thử nghiệm các hàm khác nhau ngay trực tiếp trên trình duyệt!

In [1]:
# Nhập thư viện pandas (thư viện mạnh mẽ nhất để xử lý dữ liệu bảng trong Python)
# Thường được viết tắt là pd cho ngắn gọn
import pandas as pd

## Đọc dữ liệu từ file CSV

In [2]:
# Load file csv từ thư mục máy tính

file_source = "datasets/automotive_data/data.csv"

csv_df = pd.read_csv(file_source)

In [3]:
csv_df.head()

,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.60,...,130,mpfi,3.47,2.68,9.00,111,5000,21,27,13495
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250

In [4]:
# Đọc file CSV bằng Python – không có tiêu đề 
csv_df = pd.read_csv(file_source, header=None)

In [5]:
csv_df

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [6]:
# Lấy 10 dòng đầu tiên
csv_df_10_head = csv_df.head(10)

In [7]:
csv_df_10_head

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
5,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
7,1,?,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,?

In [8]:
# Lấy 10 dòng cuối cùng
csv_df_10_tail = csv_df.tail(10)

In [9]:
csv_df_10_tail

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
195,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,13415
196,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,15985
197,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,16515
198,-2,103,volvo,gas,turbo,four,sedan,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18420
199,-1,74,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18950
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [10]:
# Thêm tiêu đề
headers = ["symboling","normalized-losses","make","fuel-type","aspiration", "num-of-doors","body-style",
         "drive-wheels","engine-location","wheel-base", "length","width","height","curb-weight","engine-type",
         "num-of-cylinders", "engine-size","fuel-system","bore","stroke","compression-ratio","horsepower",
         "peak-rpm","city-mpg","highway-mpg","price"]

csv_df.columns = headers
csv_df.head(10)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
5,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
7,1,?,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,?

In [11]:
# Xuất dataframe ra file CSV
csv_df.to_csv('./datasets/automotive_data/data_with_header.csv')

# Load file json từ thư mục máy tính

JSON là viết tắt của JavaScript Object Notation, là một kiểu định dạng dữ liệu tuân theo một quy luật nhất định mà hầu hết các ngôn ngữ lập trình hiện nay đều có thể đọc được. JSON là một tiêu chuẩn mở để trao đổi dữ liệu trên web.

Định dạng JSON sử dụng các cặp key – value để dữ liệu sử dụng. Nó hỗ trợ các cấu trúc dữ liệu như đối tượng và mảng. 

{
"employees":[
    {"firstName":"John", "lastName":"Doe"},
    {"firstName":"Anna", "lastName":"Smith"},
    {"firstName":"Peter", "lastName":"Jones"}
]
}

In [12]:
# Load file json từ thư mục máy tính
json_file = "./datasets/batdongsan.json"

In [13]:
json_df = pd.read_json(json_file)

In [14]:
json_df.head()

,beds,category,city,direction,district,news_begin_date,news_end_date,news_id,news_type_level,price,root,square,street,ward,label_price
100154,None,Nhà đất bán,Hồ Chí Minh,None,Phú Nhuận,1536537600000,1537142400000,17533924.0,Tin thường,21.0,nha_dat_thue,100m²,None,None,triệu/tháng
100316,None,Nhà đất cho thuê,Hồ Chí Minh,None,Phú Nhuận,1536192000000,1536796800000,17404807.0,Tin thường,35.0,nha_dat_thue,76m²,Đào Duy Anh,9,triệu/tháng
100394,None,Nhà đất bán,Hồ Chí Minh,None,Phú Nhuận,1536019200000,1536624000000,16807519.0,Tin thường,80.0,nha_dat_thue,144m²,Hoa Lan,2,triệu/tháng
100402,None,Nhà đất cho thuê,Hồ Chí Minh,None,Phú Nhuận,1536105600000,1536710400000,16831594.0,Tin thường,15.9,nha_dat_thue,50m²,Hoa Cau,None,triệu/tháng
100896,None,Nhà đất cho thuê,Hồ Chí Minh,None,Quận 1,1536192000000,1536796800000,17500085.0,Tin thường,420.3,nha_dat_thue,70m²,Nguyễn Công Trứ,Nguyễn Thái Bình,nghìn/m2/tháng

In [15]:
json_df_10_tail = json_df.tail(10)
json_df_10_tail

,beds,category,city,direction,district,news_begin_date,news_end_date,news_id,news_type_level,price,root,square,street,ward,label_price
98621,None,Nhà đất cho thuê,Hồ Chí Minh,None,Gò Vấp,1534809600000,1538784000000,17304165.0,Tin thường,15.0,nha_dat_thue,Không xác định,Lê Văn Thọ,None,triệu/tháng
98634,None,Nhà đất cho thuê,Hồ Chí Minh,None,Gò Vấp,1533686400000,1549238400000,17039869.0,Tin thường,10.0,nha_dat_thue,Không xác định,Lê Văn Thọ,13,triệu/tháng
98646,4+,Nhà đất cho thuê,Hồ Chí Minh,None,Gò Vấp,1533600000000,1541376000000,17039129.0,Tin thường,32.0,nha_dat_thue,157.5m²,Lê Đức Thọ,17,triệu/tháng
98759,None,Nhà đất cho thuê,Hồ Chí Minh,None,Hóc Môn,1536278400000,1536883200000,16267470.0,Tin thường,15.0,nha_dat_thue,140m²,Phan Văn Đối,Bà Điểm,triệu/tháng
9921,None,Nhà đất bán,Hà Nội,None,Cầu Giấy,1536278400000,1536883200000,17062391.0,Tin thường,29.0,nha_dat_ban,385m²,Khuất Duy Tiến,Trung Hòa,triệu/m²
99434,4+,Nhà đất cho thuê,Hồ Chí Minh,None,Phú Nhuận,1536019200000,1536624000000,17282021.0,Tin Vip 3,13.0,nha_dat_thue,75m²,Thích Quảng Đức,None,triệu/tháng
99503,2+,Nhà đất cho thuê,Hồ Chí Minh,None,Phú Nhuận,1536105600000,1536710400000,17479193.0,Tin thường,20.0,nha_dat_thue,77m²,Hoàng Minh Giám,9,triệu/tháng
99661,1+,Nhà đất cho thuê,Hồ Chí Minh,None,Phú Nhuận,1536019200000,1536624000000,11987819.0,Tin thường,15.5,nha_dat_thue,52m²,Nguyễn Văn Trỗi,12,triệu/tháng
99814,None,Nhà đất cho thuê,Hồ Chí Minh,None,Phú Nhuận,1536019200000,1536624000000,17387435.0,Tin thường,4.0,nha_dat_thue,15m²,Huỳnh Văn Bánh,10,triệu/tháng
99855,2+,Nhà đất cho thuê,Hồ Chí Minh,None,Phú Nhuận,1536105600000,1536710400000,16627347.0,Tin thường,14.0,nha_dat_thue,90m²,Phan Đăng Lưu,1,triệu/tháng

In [16]:
# Xuất dataframe ra file json
json_df_10_tail.to_json("./datasets/bds_10_tail.json")

## Đọc dữ liệu từ file excel

In [17]:
# Load file Excel từ thư mục máy tính
excel_file = "./datasets/batdongsan.xlsx"

In [18]:
excel_df = pd.read_excel(excel_file)

In [19]:
excel_df.head()

,beds,category,city,direction,district,news_begin_date,news_end_date,news_id,news_type_level,price,root,square,street,ward,label_price
0,NaN,Nhà đất bán,Hồ Chí Minh,NaN,Phú Nhuận,1536537600000,1537142400000,17533924.0,Tin thường,21.0,nha_dat_thue,100m²,NaN,NaN,triệu/tháng
1,NaN,Nhà đất cho thuê,Hồ Chí Minh,NaN,Phú Nhuận,1536192000000,1536796800000,17404807.0,Tin thường,35.0,nha_dat_thue,76m²,Đào Duy Anh,9,triệu/tháng
2,NaN,Nhà đất bán,Hồ Chí Minh,NaN,Phú Nhuận,1536019200000,1536624000000,16807519.0,Tin thường,80.0,nha_dat_thue,144m²,Hoa Lan,2,triệu/tháng
3,NaN,Nhà đất cho thuê,Hồ Chí Minh,NaN,Phú Nhuận,1536105600000,1536710400000,16831594.0,Tin thường,15.9,nha_dat_thue,50m²,Hoa Cau,NaN,triệu/tháng
4,NaN,Nhà đất cho thuê,Hồ Chí Minh,NaN,Quận 1,1536192000000,1536796800000,17500085.0,Tin thường,420.3,nha_dat_thue,70m²,Nguyễn Công Trứ,Nguyễn Thái Bình,nghìn/m2/tháng

In [20]:
excel_df_10_head = excel_df.head(10)

In [21]:
# Xuất dataframe ra file excel
excel_df_10_head.to_excel("./datasets/bds_10_head.xlsx")

## Đọc dữ liệu từ WEBSITE

In [22]:
html_url = "https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/"
html_df = pd.read_html(html_url)

In [23]:
html_df[0].head()

,Bank NameBank,CityCity,StateSt,CertCert,Acquiring InstitutionAI,Closing DateClosing,FundFund
0,Heartland Tri-State Bank,Elkhart,KS,25851,"Dream First Bank, N.A.","July 28, 2023",10544
1,First Republic Bank,San Francisco,CA,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
2,Signature Bank,New York,NY,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
3,Silicon Valley Bank,Santa Clara,CA,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
4,Almena State Bank,Almena,KS,15426,Equity Bank,"October 23, 2020",10538

# Bài tập thực hành

## Bài 1: Sử dụng pandas để đọc file 'batdongsan.xlsx'

In [24]:
# Your code

## Bài 2: Có bao nhiêu hàng trong tập dữ liệu?

In [25]:
# You code

## Bài 3: Tên các cột là gì?

In [26]:
# Your code

## Bài 4: Xuất 100 dòng đầu tiên của dataframe ra một file CSV

In [27]:
# Your code

## Bài 5: Xuất dữ liệu các cột 'city', 'district', và 'ward' thành một json file

In [28]:
# Your code