# Làm việc và tương tác với cơ sở dữ liệu

## Kết nối với cơ sở dữ liệu

### Import thư viện có thể tương tác với cơ sở dữ liệu

Trong ví dụ này chúng ta sử dụng thư viện pymssql để kết nối với cơ sở dữ liệu MSSQL. Đối với các cơ sở dữ liệu khác như Mysql, Postgres, Netteza sẽ có những thư viện python khác hỗ trợ để phục vụ việc kết nối tới các cơ sở dữ liệu.

[Tìm hiểu thêm về thư viện pymssql tại đây!](https://pymssql.readthedocs.io/en/stable/intro.html).

In [1]:
# Import thư viện cần thiết
import pymssql
import pandas as pd

### Khởi tạo một kết nối tới cơ sở dữ liệu sử dụng hàm connect trong thư viện pymssql

In [2]:
# Khai báo thông tin server name, user, password, database name để kết nối với server mssql
conn = pymssql.connect(server="sql-st.datapot.edu.vn", user="datapot_student", password="datapot@mspartner", database="adventureworks")
cursor = conn.cursor()

In [3]:
# Chạy câu lệnh SQL để truy vấn dữ liệu
cursor.execute ("SELECT * from [adventureworks].[SalesLT].[Customer]")

In [4]:
# Kiểm tra các tên cột của bảng customer trong db adventurework
num_fields = len(cursor.description)
field_names = [i[0] for i in cursor.description]
print(field_names)

['CustomerID', 'NameStyle', 'Title', 'FirstName', 'MiddleName', 'LastName', 'Suffix', 'CompanyName', 'SalesPerson', 'EmailAddress', 'Phone', 'PasswordHash', 'PasswordSalt', 'rowguid', 'ModifiedDate']

In [5]:
# Lấy toàn bộ dữ liệu trong database
row = cursor.fetchall()
print("Mẫu dữ liệu lấy được: \n",row[1])
print("Đếm kích thước của bảng customer: ", len(row))

Mẫu dữ liệu lấy được:
 (2, False, 'Mr.', 'Keith', None, 'Harris', None, 'Progressive Sports', 'adventure-works\\david8', 'keith0@adventure-works.com', '170-555-0127', 'YPdtRdvqeAhj6wyxEsFdshBDNXxkCXn+CRgbvJItknw=', 'fs1ZGhY=', UUID('e552f657-a9af-4a7d-a645-c429d6e02491'), datetime.datetime(2006, 8, 1, 0, 0))
Đếm kích thước của bảng customer:  847

In [6]:
# Tạo một pandas dataframe từ kết quả và tên cột đã lấy được
df = pd.DataFrame(row, columns=field_names)
df.head()

,CustomerID,NameStyle,Title,FirstName,MiddleName,LastName,Suffix,CompanyName,SalesPerson,EmailAddress,Phone,PasswordHash,PasswordSalt,rowguid,ModifiedDate
0,1,False,Mr.,Orlando,N.,Gee,None,A Bike Store,adventure-works\pamela0,None,245-555-0173,L/Rlwxzp4w7RWmEgXX+/A7cXaePEPcp+KwQhl2fJL7w=,1KjXYs4=,3f5ae95e-b87d-4aed-95b4-c3797afcb74f,2005-08-01
1,2,False,Mr.,Keith,None,Harris,None,Progressive Sports,adventure-works\david8,keith0@adventure-works.com,170-555-0127,YPdtRdvqeAhj6wyxEsFdshBDNXxkCXn+CRgbvJItknw=,fs1ZGhY=,e552f657-a9af-4a7d-a645-c429d6e02491,2006-08-01
2,3,False,Ms.,Donna,F.,Carreras,None,Advanced Bike Components,adventure-works\jillian0,donna0@adventure-works.com,279-555-0130,LNoK27abGQo48gGue3EBV/UrlYSToV0/s87dCRV7uJk=,YTNH5Rw=,130774b1-db21-4ef3-98c8-c104bcd6ed6d,2005-09-01
3,4,False,Ms.,Janet,M.,Gates,None,Modular Cycle Systems,adventure-works\jillian0,janet1@adventure-works.com,710-555-0173,ElzTpSNbUW1Ut+L5cWlfR7MF6nBZia8WpmGaQPjLOJA=,nm7D5e4=,ff862851-1daa-4044-be7c-3e85583c054d,2006-07-01
4,5,False,Mr.,Lucy,None,Harrington,None,Metropolitan Sports Supply,adventure-works\shu0,lucy0@adventure-works.com,828-555-0186,KJqV15wsX3PG8TS5GSddp6LFFVdd3CoRftZM/tP0+R4=,cNFKU4w=,83905bdc-6f5e-4f71-b162-c98da069f38a,2006-09-01

In [7]:
# Sau khi truy vấn thành công, tắt session kết nối sau khi không có nhu cầu sử dụng
cursor.close()
conn.close()

In [8]:
# Tổng hợp toàn bộ các bước nhỏ thành một luồng tổng thể:
import pymssql
import pandas as pd
try:
    conn = pymssql.connect(server="sql-st.datapot.edu.vn", user="datapot_student", password="datapot@mspartner", database="adventureworks")
    cursor = conn.cursor()
    cursor.execute ("SELECT * from [adventureworks].[SalesLT].[Customer]")
    num_fields = len(cursor.description)
    field_names = [i[0] for i in cursor.description]
    row = cursor.fetchall()
    df = pd.DataFrame(row, columns=field_names)
    cursor.close()
    conn.close()
except Exception:
    print("\nERROR: Unable to connect to the server.")
    exit(-1)
    
df.head()

,CustomerID,NameStyle,Title,FirstName,MiddleName,LastName,Suffix,CompanyName,SalesPerson,EmailAddress,Phone,PasswordHash,PasswordSalt,rowguid,ModifiedDate
0,1,False,Mr.,Orlando,N.,Gee,None,A Bike Store,adventure-works\pamela0,None,245-555-0173,L/Rlwxzp4w7RWmEgXX+/A7cXaePEPcp+KwQhl2fJL7w=,1KjXYs4=,3f5ae95e-b87d-4aed-95b4-c3797afcb74f,2005-08-01
1,2,False,Mr.,Keith,None,Harris,None,Progressive Sports,adventure-works\david8,keith0@adventure-works.com,170-555-0127,YPdtRdvqeAhj6wyxEsFdshBDNXxkCXn+CRgbvJItknw=,fs1ZGhY=,e552f657-a9af-4a7d-a645-c429d6e02491,2006-08-01
2,3,False,Ms.,Donna,F.,Carreras,None,Advanced Bike Components,adventure-works\jillian0,donna0@adventure-works.com,279-555-0130,LNoK27abGQo48gGue3EBV/UrlYSToV0/s87dCRV7uJk=,YTNH5Rw=,130774b1-db21-4ef3-98c8-c104bcd6ed6d,2005-09-01
3,4,False,Ms.,Janet,M.,Gates,None,Modular Cycle Systems,adventure-works\jillian0,janet1@adventure-works.com,710-555-0173,ElzTpSNbUW1Ut+L5cWlfR7MF6nBZia8WpmGaQPjLOJA=,nm7D5e4=,ff862851-1daa-4044-be7c-3e85583c054d,2006-07-01
4,5,False,Mr.,Lucy,None,Harrington,None,Metropolitan Sports Supply,adventure-works\shu0,lucy0@adventure-works.com,828-555-0186,KJqV15wsX3PG8TS5GSddp6LFFVdd3CoRftZM/tP0+R4=,cNFKU4w=,83905bdc-6f5e-4f71-b162-c98da069f38a,2006-09-01

# Bài tập Thực hành

## Bài 1: Thực hành kết nối với database `[AdventureWorksDW2020].[dbo].[FactInternetSales]`

In [12]:
# Viết đoạn code của bạn ở đây

## Bài 2: Tìm Kích thước của bảng FactInternetSales (Số hàng + Số cột)

In [13]:
# Viết đoạn code của bạn ở đây

## Bài 3: Xuất 100 hàng bất kỳ từ bảng FactInternetSales chứa thông tin các cột: `SalesOrderNumber`, `OrderDate`, `ShipDate`, `OrderQuantity`, `UnitPrice`, `TotalProductCost`  ra file csv

In [14]:
# Viết đoạn code của bạn ở đây